In [1]:
import torch

In [2]:
voxel_ids = torch.arange(0, 10)
print(voxel_ids.shape)
print(voxel_ids[:, None, None].shape)
print(voxel_ids[None, :].shape)

torch.Size([10])
torch.Size([10, 1, 1])
torch.Size([1, 10])


In [7]:

overlaps = torch.randn([10, 6])
print(overlaps)
max_overlaps, max_overlaps_idx = torch.max(overlaps, dim=1)
print(max_overlaps)
print(max_overlaps_idx)

tensor([[ 1.0365,  0.3905, -1.2539, -1.6479, -0.6429, -1.6476],
        [-0.4283, -1.4024, -0.6467, -0.7114,  0.9381, -0.2706],
        [-0.8729,  0.6905, -0.4428, -1.6551,  1.1333,  2.3888],
        [ 0.9877, -0.6946, -0.0646, -1.4754,  0.4090,  0.3467],
        [-0.9343,  1.1441,  1.4833, -0.4735, -0.6936, -1.6264],
        [ 0.3553,  0.2171, -1.6461, -1.3843,  0.4671, -0.0641],
        [ 0.8414,  0.1557, -0.1272,  1.4650,  0.2490,  1.7875],
        [ 1.5504, -0.6283,  0.6168, -0.8507,  0.0860,  0.5486],
        [ 0.0194,  1.2220, -0.5570,  1.3958,  0.4810, -1.4545],
        [-1.1150,  1.7753, -0.1107,  0.6534,  1.5008,  1.0142]])
tensor([1.0365, 0.9381, 2.3888, 0.9877, 1.4833, 0.4671, 1.7875, 1.5504, 1.3958,
        1.7753])
tensor([0, 4, 5, 0, 2, 4, 5, 0, 3, 1])
